---
  - name: Update and upgrade apt packages
    become: true
    apt:
        upgrade: yes
        update_cache: yes

  - name: Install JRE
    become: true
    apt:
      name: openjdk-17-jre
      state: latest
  
  - name: Install dos2unix
    become: true
    apt:
      name: dos2unix
      state: present
  
  - name: Install MySQL client
    become: true
    apt:
      name: mysql-client
      state: present

  - name: Create log file
    file:
        path: /var/log/petclinic.log
        state: touch
        mode: '0777'