---
- name: Install Python3 and pip3
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Install AWS CLI using pip3
  become: true
  command: python3 -m pip install awscli --break-system-packages

- name: Install boto3 using pip3
  become: true
  command: python3 -m pip install boto3 --break-system-packages

- name: Install PyMySQL using pip3
  become: true
  command: python3 -m pip install PyMySQL --break-system-packages